### ISSUE TITLE
server crash after completed intent

### ISSUE THREAD

**Issue by wczub** [CSUMB-SP17-CST499/PLex-Chatbot#34]
After adding a chair to the kitchen with attributes, if you type anything afterwards it crashes the server.
This means after you receive the "Thanks, your 30 USD chair will be added to the kitchen." if you type more, then it will crash the server. 

> TypeError: Cannot read property 'name' of undefined
>     at TextRequest.<anonymous> (/Chatbot/server/utilities/apiai.js:39:118)

**Comment by yarelyc** [comment]
Thanks, will take a look at this :)

**Comment by yarelyc** [comment]
Note: This was fixed with sessionId
